<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class SuperModel extends Model
{
    use HasFactory;

    protected function asJson($value)
    {
        return json_encode($value, JSON_UNESCAPED_UNICODE);
    }

    public function toJson($options = 0)
    {
        return parent::toJson(JSON_UNESCAPED_UNICODE); // TODO: Change the autogenerated stub
    }
}
